<?php
/**
 * @file
 * Install, update and uninstall functions for the vchess module.
 *
 */

/**
 * Implements hook_install()
 */
function vchess_install() {
  // rid=2 => authenticated user
  user_role_change_permissions('authenticated',
    [
      'view player' => TRUE,
      'basic access' => TRUE,
      'view game' => TRUE, 
      'view challenges' => TRUE,
      'accept challenge' => TRUE, 
      'my current games' => TRUE,
     ]
   );
}
