<?php

/**
 * @file
 * Drupal chess module
 * VChess is based on OCC chess by Michael Speck
 * VChess for Drupal 7 is based on VChess for Drupal 6 by Andrej Prochazka
 *
 */

// VChess module files
use Drupal\vchess\Game\Piece;

global $base_url; // e.g. http://localhost/chess_drupal-7.14

define("VCHESS_PENDING_LIMIT", 3);

// During testing, it is sometimes useful to allow the possiblity to play against
// oneself.
define("MAY_PLAY_SELF", FALSE);

// Only set the error display on if debugging locally
if (strpos($base_url, "localhost") > 0) {
  ini_set('display_errors', 'On');
  error_reporting(E_ALL);
}

/**
 * Display help and module information
 */
function vchess_help($path, $arg) {
  if ($path == 'admin/help#vchess') {
    $txt = t('VChess module.  Chess games between site users');
    return $txt;
  }
}

/**
 * Implements hook_theme().
 */
function vchess_theme($existing, $type, $theme, $path) {
  return [
    'vchess_captured_pieces' => [
      'variables' => ['pieces' => NULL, 'board_theme' => NULL],
    ],
    'vchess_game_timer' => [
      'variables' => [
        'name' => NULL,
        'title' => NULL,
        'player' => NULL,
        'white_name' => NULL,
        'black_name' => NULL,
        'white_time' => NULL,
        'black_time' => NULL,
      ],
    ],
  ];
}
