<?php

/**
 * @file
 * Drupal gamer module
 */

require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'gamer') . '/rating.inc';
require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'gamer') . '/player.inc';

/**
 * hook_menu() implementation
 */
function gamer_menu() {
  $items = array();
  
  $items['gamer/players'] = array(
      'page callback' => 'gamer_players',
      'access arguments' => array('view players table'),
      'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * menu callback gamer_players to display a list of all players
 */
function gamer_players() {
  $sql = "SELECT uid FROM {users} ORDER BY name";
  // Converted to the D7 database API syntax.
  $result = db_query($sql);
  foreach ($result as $record) {
    if ($record->uid <> 0) {
      $player_stats = gamer_load_user_stats($record->uid);
      $stats[] = array(
          $record->uid,
          "<a href='" . url("vchess/player/" . $player_stats['name']) . "'>" . $player_stats['name'] . "</a>",
          $player_stats['rating'],
          $player_stats['played'],
          $player_stats['won'],
          $player_stats['lost'],
          $player_stats['drawn'],
          $player_stats['rchange'],
          $player_stats['current']
      );
    }
  }

  $table['header'] = array('uid', 'name', 'rating', 'played', 'won', 'lost', 'drawn', 'rating change', 'current');
  $table['attributes'] = array();
  $table['caption'] = array();
  $table['colgroups'] = array();
  $table['sticky'] = "";
  $table['empty'] = "The message to display in an extra row if table does not have any rows.";
  $table['rows'] = $stats;

  //  ['name'], $stats['wins'], $stats['draws'],
  //$stats['losses'], $stats['rating'], $stats['rgames'], $stats['rchange']);

  return theme_table($table);
}

/**
 * Get the stats table for a single player
 */
function gamer_player_stats($uid) {
  $stats = gamer_load_user_stats($uid);

  $header = array('Played', 'Won', 'Drawn', 'Lost', 'Rating', 'Rating change', 'Current');
  $rows = array(array($stats['played'], $stats['won'], $stats['drawn'],
      $stats['lost'], $stats['rating'], $stats['rchange'], $stats['current']));

  $player = user_load($uid);

  $html = "Here are the full statistics for <b>" . $player->name . "</b>:";

  $html .= theme_table(array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'caption' => array(),
      'colgroups' => array(),
      'sticky' => array(),
      'empty' => NULL
  ));

  return $html;
}

