<?php

/**
 * @file
 * Drupal gamer module
 */

require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'gamer') . '/rating.inc';
require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'gamer') . '/player.inc';

require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'tsort') . '/tsort.module';

/**
 * hook_menu() implementation
 */
function gamer_menu() {
  $items = array();
  
  $items['gamer/players'] = array(
      'page callback' => 'gamer_players',
      'access arguments' => array('view players table'),
      'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * menu callback gamer_players to display a list of all players
 */
function gamer_players() {
  $sql = "SELECT uid FROM {users} ORDER BY name";
  // Converted to the D7 database API syntax.
  $result = db_query($sql);
  foreach ($result as $record) {
    if ($record->uid <> 0) {
      $player_stats = gamer_load_user_stats($record->uid);
      $stats[] = array(
          'uid' => $record->uid,
          'name' => "<a href='" . url("vchess/player/" . $player_stats['name']) . "'>" . $player_stats['name'] . "</a>",
          'rating' => $player_stats['rating'],
          'played' => $player_stats['played'],
          'won' => $player_stats['won'],
          'lost' => $player_stats['lost'],
          'drawn' => $player_stats['drawn'],
          'rating_change' => $player_stats['rchange'],
          'current' => $player_stats['current']
      );
    }
  }

  $header = array(
      array('data' => t('uid'), 'field' => 'uid'),
      array('data' => t('name'), 'field' => 'name'),
      array('data' => t('rating'), 'field' => 'rating'),
      array('data' => t('played'), 'field' => 'played'),
      array('data' => t('won'), 'field' => 'won'),
      array('data' => t('lost'), 'field' => 'lost'),
      array('data' => t('drawn'), 'field' => 'drawn'),
      array('data' => t('rating change'), 'field' => 'rating_change'),
      array('data' => t('in progress'), 'field' => 'current')
  );
  
  // getting the current sort and order parameters from the url
  // e.g. q=vchess/my_current_games&sort=asc&order=White
  $order = tablesort_get_order($header);
  $sort = tablesort_get_sort($header);
  
  // sort the table data accordingly
  $stats = tsort_nonsql_sort($stats, $sort, $order['sql']);
  
  $table['header'] = $header;
  $table['attributes'] = array();
  $table['caption'] = "";
  $table['colgroups'] = array();
  $table['sticky'] = "";
  $table['empty'] = "The message to display in an extra row if table does not have any rows.";
  $table['rows'] = $stats;

  return theme_table($table);
}

/**
 * Get the stats table for a single player
 * 
 * @param $uid
 *   User id of player for whom stats are wanted
 *   
 * @return $html
 *   A themed table of the statistics
 */
function gamer_player_stats($uid) {
  $stats = gamer_load_user_stats($uid);

  $header = array('Played', 'Won', 'Drawn', 'Lost', 'Rating', 'Rating change', 'Current');
  $rows = array(array($stats['played'], $stats['won'], $stats['drawn'],
      $stats['lost'], $stats['rating'], $stats['rchange'], $stats['current']));

  $player = user_load($uid);

  $html = "Here are the full statistics for <b>" . $player->name . "</b>:";

  $html .= theme_table(array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'caption' => array(),
      'colgroups' => array(),
      'sticky' => array(),
      'empty' => NULL
  ));

  return $html;
}

